### ISSUE TITLE
example.html showing blank page only

### ISSUE THREAD

**Issue by ayswaryaprsd** [d4nyll/instafetch#1]
When i am trying to run example.html it showing a blank page only :(

**Comment by d4nyll** [comment]
This is as expected. The results are logged in the console. You can see the results by checking in your console.

When you use Instafetch, simply swap out the `console.log()` functions with your functions.

But you made a good point that it's not so obvious to look there, so I have added some changes adding in instructions and explanation in the example itself. Hope this helps.

**Comment by ayswaryaprsd** [comment]
I am sorry to ask again.I know this is a stupid question.but i didnt get you..what you mean by console?Console means the official api??
  I am using this api to get the follower details.not  media.when i am using the official instagram api  that returns only 100 results in a page.

**Comment by d4nyll** [comment]
Console means the Developer's console in your browser. Press <kbd>F12</kbd> and it'll probably open up.

This doesn't get follower details, only media. If you want this feature, you can create a new issue and I will work on it when I have the time.
