### ISSUE TITLE
Sample markup creation? 

### ISSUE THREAD

**Issue by toobulo** [d4nyll/instafetch#2]
Hi there,

Very cool workaround to get beyond the Instagram limit.  Do you have a simple example somewhere which shows how to output the results into HTML?  

Thanks!

**Comment by d4nyll** [comment]
I can certainly do that! Stay tuned!

**Comment by d4nyll** [comment]
You can find an example at http://d4nyll.github.io/instafetch/, the source code for that page is in the `examples` directory.
